services:
  tomochan:
    build:
      context: ./
    container_name: tomochan
    environment:
      TZ: "Europe/Warsaw"
      NODE_ENV: "production"
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      TOMO_ID: ${TOMO_ID}
      OWNER_ID: ${OWNER_ID}
    volumes:
      - ./db/:/usr/src/app/db/