services:
  tomochan:
    build:
      context: ./
    container_name: tomochan
    environment:
      TZ: "Europe/Warsaw"
      NODE_ENV: "production"
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      TOMO_ID: ${TOMO_ID}
      OWNER_ID: ${OWNER_ID}
      DATABASE_URL: ${DATABASE_URL}
      NOTIFICATIONS_CHANNEL_ID: ${NOTIFICATIONS_CHANNEL_ID}