services:
  tomochan:
    build:
      context: ./
    container_name: tomochan
    environment:
      TZ: "Europe/Warsaw"
      NODE_ENV: "production"
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      TOMO_ID: ${TOMO_ID}
      OWNER_ID: ${OWNER_ID}
      DATABASE_URL: ${DATABASE_URL}
      NOTIFICATIONS_CHANNEL: ${NOTIFICATIONS_CHANNEL}
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  pgdata:
  
networks:
  default:
    driver: bridge